export const SET_ACTIVE_MENU_INDEX = "SET_ACTIVE_MENU_INDEX";

export const REQUEST_HOME_CONTENT = "REQUEST_HOME_CONTENT";
export const RECEIVE_HOME_CONTENT = "RECEIVE_HOME_CONTENT";

export const REQUEST_HOME_INFORMATION = "REQUEST_HOME_INFORMATION";
export const RECEIVE_HOME_INFORMATION = "RECEIVE_HOME_INFORMATION";

export const REQUEST_PROFILE_TUTOR = "REQUEST_PROFILE_TUTOR";
export const RECEIVE_PROFILE_TUTOR = "RECEIVE_PROFILE_TUTOR";

export const REQUEST_PROFILE_REASON = "REQUEST_PROFILE_RESSON";
export const RECEIVE_PROFILE_REASON = " RECEIVE_PROFILE_REASON";

export const REQUEST_PROFILE_IDEA = "REQUEST_PROFILE_IDEA";
export const RECEIVE_PROFILE_IDEA = "RECEIVE_PROFILE_IDEA";

export const REQUEST_PROFILE_STRUCT = "REQUEST_PROFILE_STRUCT";
export const RECEIVE_PROFILE_STRUCT = "RECEIVE_PROFILE_STRUCT";

export const REQUEST_TEACHING_STAFF = "REQUEST_TEACHING_STAFF";
export const RECEIVE_TEACHING_STAFF = "RECEIVE_TEACHING_STAFF";

export const REQUEST_TEACHING_COURSE = "REQUEST_TEACHING_COURSE";
export const RECEIVE_TEACHING_COURSE = "RECEIVE_TEACHING_COURSE";

export const REQUEST_TEACHING_MORAL = "REQUEST_TEACHING_MORAL";
export const RECEIVE_TEACHING_MORAL = "RECEIVE_TEACHING_MORAL";

export const REQUEST_TEACHING_INTERNSHIP = "REQUEST_TEACHING_INTERNSHIP";
export const RECEIVE_TEACHING_INTERNSHIP = "RECEIVE_TEACHING_INTERNSHIP";

export const REQUEST_TEACHING_RESOURCE = "REQUEST_TEACHING_RESOURCE";
export const RECEIVE_TEACHING_RESOURCE = "RECEIVE_TEACHING_RESOURCE";

export const REQUEST_LIFE_SCENERY = "REQUEST_LIFE_SCENERY";
export const RECEIVE_LIFE_SCENERY = "RECEIVE_LIFE_SCENERY";

export const REQUEST_LIFE_FACILITIES = "REQUEST_LIFE_FACILITIES";
export const RECEIVE_LIFE_FACILITIES = "RECEIVE_LIFE_FACILITIES";

export const REQUEST_LIFE_LEARNING = "REQUEST_LIFE_LEARNING";
export const RECEIVE_LIFE_LEARNING = "RECEIVE_LIFE_LEARNING";

export const REQUEST_LIFE_SILHOUETTE = "REQUEST_LIFE_SILHOUETTE";
export const RECEIVE_LIFE_SILHOUETTE = "RECEIVE_LIFE_SILHOUETTE";

export const REQUEST_LIFE_DAILYLIFE = "REQUEST_LIFE_DAILYLIFE";
export const RECEIVE_LIFE_DAILYLIFE = "RECEIVE_LIFE_DAILYLIFE";

export const REQUEST_ENROLLMENT_RECRUIT = "REQUEST_ENROLLMENT_RECRUIT";
export const RECEIVE_ENROLLMENT_RECRUIT = "RECEIVE_ENROLLMENT_RECRUIT";

export const REQUEST_ENROLLMENT_EMPLOYMENT = "REQUEST_ENROLLMENT_EMPLOYMENT";
export const RECEIVE_ENROLLMENT_EMPLOYMENT = "RECEIVE_ENROLLMENT_EMPLOYMENT";

export const REQUEST_ENROLLMENT_ALUMNI = "REQUEST_ENROLLMENT_ALUMNI";
export const RECEIVE_ENROLLMENT_ALUMNI = "RECEIVE_ENROLLMENT_ALUMNI";

export const REQUEST_NEWS_2019 = "REQUEST_NEWS_2019";
export const RECEIVE_NEWS_2019 = "RECEIVE_NEWS_2019";
export const REQUEST_NEWS_2018 = "REQUEST_NEWS_2018";
export const RECEIVE_NEWS_2018 = "RECEIVE_NEWS_2018";

export const REQUEST_CONTACT = "REQUEST_CONTACT";
export const RECEIVE_CONTACT = "RECEIVE_CONTACT";

export const REQUEST_CONTACT_OPENDAY = "REQUEST_CONTACT_OPENDAY";
export const RECEIVE_CONTACT_OPENDAY = "RECEIVE_CONTACT_OPENDAY";

export const REQUEST_CONTACT_SPONSOR = "REQUEST_CONTACT_SPONSOR";
export const RECEIVE_CONTACT_SPONSOR = "RECEIVE_CONTACT_SPONSOR";
